form3tech-oss/chaos-mesh

- CHANGELOG.md
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
* fix: set `replicas: 1` automatically when HA is not enabled
* Update CHANGELOG.md
---------
```shell
```
> fix: set `replicas: 1` automatically when HA is not enabled (#4079)

- .github/workflows/ci.yaml
Removes hardcoded tag version in the release comment
```shell
```
> fix: remove hardcoded tag version from release comment

- controllers/chaosimpl/k8schaos/impl.go
ticket: https://github.com/form3tech/sre-guild-team/issues/497
Ensures that:
- A resource namespace is explicitly passed when interacting with the k8s api via an `unstructured.Unstructured` object.  If this is not done then a cluster level scoping is assumed.
- K8SChaos only deletes resources that it has created (i.e. those that it manages)
```shell
```
> Use namespace in unstructured objects and track/enforce k8schaos resource management

- .github/workflows/calculate_tag.yaml
> fix: use `release` in tag name not `test`

- images/chaos-daemon/Dockerfile
Allow running I/O chaos experiments on containers with readonly root filesystem.
```shell
```
> chore: use form3tech-oss/toda in chaos-daemon build

- helm/chaos-mesh/templates/_helpers.tpl
- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/values.schema.json
- helm/chaos-mesh/values.yaml
- install.sh
- pkg/log/zap.go
- pkg/log/zap_test.go
The original aim here was to prevent log lines long enough to cause `fluentd` to fail to ingest logs. After working out a solution, it became apparent that more logging configuration would also be desirable.
Configure structured logging and conventional field names for timestamp, level, etc.
Truncate log fields over a certain limit.
Allow configuration of key logging parameters through environment.
```shell
```
> fix: improve zap logging configuration

- api/v1alpha1/schedule_webhook.go
- api/v1alpha1/zz_generated.chaosmesh.go
- cmd/chaos-builder/impl.go
- controllers/common/condition/controller.go
- controllers/common/desiredphase/controller.go
- controllers/common/finalizers/controller.go
- controllers/common/pipeline/pipeline.go
- controllers/common/records/controller.go
- controllers/multicluster/remotechaos/fx.go
By making these messages debug level, we can stop sending them to logz.io
> chore: Change noisy log messages to debug level

- pkg/workflow/controllers/serial_node_reconciler.go
If status check node aborted and has "abort with statuscheck" flag set, don't spawn a new workflow child node for the next step.
This fixes a race condition where the serial reconciler spawns a new child node in the window between the statuscheck node aborting and the abort status being propagated to the parent.
```shell
```
> fix: don't spawn new workflow child on abort

- pkg/metrics/chaos-controller-manager.go
We need to be careful about cardinality, but since we won't have hundreds of chaos experiments it should be ok to add name, given that is really useful for dashboards and alerting
Removed the expCache to simplify code
```shell
```
> chore: Add name label to chaos_experiments metric

- api/v1alpha1/k8schaos_types.go
- config/crd/bases/chaos-mesh.org_k8schaos.yaml
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_k8schaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd.yaml
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
Duration must be optional, I think we lost this fix in the upstream sync / rebase before christmas
> fix: k8sChaos duration should be optional

- api/v1alpha1/ciliumchaos_types.go
- config/crd/bases/chaos-mesh.org_ciliumchaos.yaml
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_ciliumchaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd.yaml
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
> fix: cilium chaos duration should be optional

- .github/workflows/integration_test.yaml
- pkg/workflow/controllers/suite_test.go
> chore: Add certLoader to test suite

- .github/workflows/check_md_links.yaml
> chore: fix link checker

- api/v1alpha1/certificatechaos_types.go
- config/crd/bases/chaos-mesh.org_certificatechaos.yaml
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- controllers/chaosimpl/certificatechaos/impl.go
- helm/chaos-mesh/crds/chaos-mesh.org_certificatechaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd.yaml
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
Avoid endless loop for unchanged cert.  If the certificate details have not changed, skip the ready check.
Additionally, make the `CertificateExpiry` and `RenewBefore` fields required, not optional, and remove default values.
> chore: Improve handling of unchanged certificates

- controllers/chaosimpl/cloudstackhost/hoststop/impl.go
Chaos unable to recover, stuck in infinite loop.
Previously, when no hosts were found that are shut down, the recovery phase would fail.
Now, in this case the recovery phase would be considered successful. 
```shell
```
> fix: update cloudstack host-stop recover to work when all hosts are up

- controllers/chaosimpl/cloudstackhost/hoststop/impl.go
- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- install.sh
Cloudstack Host chaos does not correctly fully recover:
- it does not start stopped VMs
- it does not uncordon nodes from VMs affected by the chaos
https://github.com/form3tech/payport-plus/issues/18 
- When a cloudstack VM is down, it is not assigned to any Host, so it will not be returned when listing all VMs by Host, fix this by filtering by state instead of hostId
- Restarting all VMs when Host is up is unnecessary - start only stopped VMs
- Injection step would be considered successful even if there are no matching hosts (to recover system)
- VM and system VM recovery can happen even if all hosts are up (e.g. manually turned on)
- Apply dryRun to all recovery steps
- Uncordon k8s nodes affected by the chaos
Logs:
All nodes healthy:
> This PR should be cherry-picked to the following …
> feat: update cs host chaos to better recover

- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/templates/chaos-daemon-rbac.yaml
- helm/chaos-mesh/templates/chaos-daemon-service.yaml
- helm/chaos-mesh/values.yaml
- install.sh
Adds a flag in values file, to make deploying the chaos-damon component optional
```
chaosDaemon:
create: true
```
Local test using Tilt, setting flags in Tiltfile:
Depends On:
- https://github.com/form3tech-oss/chaos-mesh/pull/89
> chore: Add flag to create or disable chaos daemon

- .github/workflows/ci.yaml
- Currently, with a large matrix job and several optional tests there are not good required checks for PRs as they can often be skipped.
- This PR allows setting a single required check that alongside a few other required checks ensures the tests either run when needed or are skipped when not and the PRs are correctly blocked in both cases if there is an issue with the checks.
- The single job will verify that required jobs have succeeded and the optional ones either succeeded or were skipped, which happens when their conditions are not fulfilled and is expected for some PRs.
- Adding a few other jobs to required checks means there shouldn't be a scenario where jobs that are supposed to run were skipped or failed and the PR is mergeable. 
> This PR should be cherry-picked to the following …
> fix: Add a common check to use as a required check

- pkg/webhook/validate_auth.go
We experienced problems in our GKE and AKS stacks, where user authentication does not work correctly creating chaos-mesh CRDs.
We received errors such as:
`Error from server (Forbidden): error when creating "/experiment.yaml": admission webhook "vauth.kb.io" denied the request: user@form3.tech is forbidden on namespace test`
On investigation, we identified that the validating webooks are at fault, since they do not pass all user information: `username` and `groups` are passed, but not `extra` field which contains cloud provider specific auth tokens.
This PR adds `extra` field to the request.  Tested in the development stacks and worked as expected.
Test can be reproduced by creating a SAR with the following bash command:
```
kubectl --context my-gke-stack auth whoami -o json | jq '{ …
```
> chore: Add support for extra in validating webhook

- api/v1alpha1/nodeselectorchaos_types.go
- config/crd/bases/chaos-mesh.org_nodeselectorchaos.yaml
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- controllers/chaosimpl/nodeselectorchaos/impl.go
- helm/chaos-mesh/crds/chaos-mesh.org_nodeselectorchaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd.yaml
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
Currently, the recovery step might remove the annotation too early. It will be a no-op and a cleanup step will be used instead. To this end, the value is now optional.
<details><summary>chaos.yml</summary>
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
name: az-loss
spec:
schedule: '0/5 * * * *' 
historyLimit: 1
concurrencyPolicy: 'Forbid'
startingDeadlineSeconds: 1
type: 'Workflow'
workflow:
entry: az-loss-workflow-entry
templates:
- name: az-loss-workflow-entry
templateType: Serial
deadline: 5m
children:
- eu-west-2a-az-chaos-20m
- eu-west-2a-az-chaos-default
- name: eu-west-2a-az-chaos-20m
templateType: NodeSelectorChaos …
> fix: Fix recover step for NodeSelectorChaos
